### ISSUE TITLE
Undefined symbols during linking

### ISSUE THREAD

**Issue by moritzhaag** [mongodb-labs/mangrove#32]
I tried to compile a simple test (see attachment). Unfortunately, I get always the following error:

Undefined symbols for architecture x86_64:
  "boson::v_noabi::bson_output_streambuf::bson_output_streambuf(std::__1::function<void (bsoncxx::v_noabi::document::value)>)", referenced from:
      boson::v_noabi::bson_ostream::bson_ostream(std::__1::function<void (bsoncxx::v_noabi::document::value)>) in MangroveTest.cpp.o
  "bsoncxx::v_noabi::builder::core::key_view(core::v1::basic_string_view<char, std::__1::char_traits<char> >)", referenced from:
      mangrove::v_noabi::model<Entry, bsoncxx::v_noabi::oid>::save() in MangroveTest.cpp.o
      boson::BSONOutputArchive::writeName(bool) in MangroveTest.cpp.o
  "bsoncxx::v_noabi::builder::core::key_owned(std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char> >)", referenced from:
      boson::BSONOutputArchive::writeName(bool) in MangroveTest.cpp.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I use the following compiler:
Apple LLVM version 7.3.0 (clang-703.0.29)
Target: x86_64-apple-darwin15.6.0

The drivers (MongoC and MongoCXX) as well as Mangrove are installed with the same prefix and the lib subdirectory is exported in DYLD_LIBRARY_PATH

Please let me know, whether I miss something in my CMakeLists file. 

[MangroveTest.zip](https://github.com/mongodb-labs/mangrove/files/406587/MangroveTest.zip)

**Comment by adamchel** [comment]
Did you also use clang to compile Mangrove and the drivers?

I get similar linking errors when the drivers and Mangrove are compiled with GCC but my sample program is compiled with Clang. You can't yet build Mangrove in a way that's binary compatible with another compiler.

**Comment by moritzhaag** [comment]
I compiled all components with the same settings and compiler. Is it possible that I need a special commit from the mongocxx master branch? Right now Im on the latest commit.

**Comment by adamchel** [comment]
I've been able to reproduce your issue, it seems to be an issue with clang linking that doesn't occur when we're running the examples. I'll be looking into it tomorrow so I'll get back to you soon. For now though, you can try using GCC (which you can install with `brew install g++-6` if you have homebrew) by invoking cmake with `-DCMAKE_C_COMPILER=gcc-6 -DCMAKE_CXX_COMPILER=g++-6`. If you do this you'll also have to recompile and reinstall Mangrove with GCC.

**Comment by moritzhaag** [comment]
Ok. Thank you very much for the quick response! 
I was also able to compile the tests and examples, so I thought the compiler may not be the problem. But then I will try it with GCC.

**Comment by adamchel** [comment]
I was able to fix the issue you were having by ensuring that the C++ driver was installed with clang, ensuring that Mangrove was being built with clang and linking with the clang-built C++ driver, and ensuring that MangroveTest was built with clang and linking with the clang-built Mangrove. 

If you're sure that you're doing this, maybe also make sure that you're linking with the same standard library in each step (use `-stdlib=libc++`). Apparently if you're at an OS X version before Mavericks, [the default standard library is libstdc++](http://stackoverflow.com/questions/19774778/when-is-it-necessary-to-use-use-the-flag-stdlib-libstdc), which you don't want.

Let me know if this doesn't work.

**Comment by moritzhaag** [comment]
Thank you very much for your effort. As I am on the most recent OS X version I tried again to compile the C driver, the C++ driver and Mangrove making sure that all use the same Apple clang compiler and now it worked. I'm sorry for the confusion.
