### ISSUE TITLE
won't find libson-config.cmake regardless of directory flag

### ISSUE THREAD

**Issue by alexge233** [mongodb-labs/mangrove#36]
Hi,

I've manually installed `libbson`, `mongo-c-driver` and `mongo-cxx-driver` using their respective `master` branches from github.

They are all installed under `/usr/local/*` and I've kept their respective build directories (in my home dir) just in case.
Regardless of passing the actual directory to cmake, I keep getting:

```
-- No build type selected, default is Release
CMake Error at CMakeLists.txt:97 (find_package):
  By not providing "FindLibBSON.cmake" in CMAKE_MODULE_PATH this project has
  asked CMake to find a package configuration file provided by "LibBSON", but
  CMake did not find one.

  Could not find a package configuration file provided by "LibBSON"
  (requested version 1.3.4) with any of the following names:

    LibBSONConfig.cmake
    libbson-config.cmake

  Add the installation prefix of "LibBSON" to CMAKE_PREFIX_PATH or set
  "LibBSON_DIR" to a directory containing one of the above files.  If
  "LibBSON" provides a separate development package or SDK, be sure it has
  been installed.
```

The cmake modules for the aforementioned libraries are (by default) installed in:

```
s -l /usr/local/lib/cmake/
total 24
drwxr-xr-x 2 root root 4096 Jul 17 14:46 libbson-1.0
drwxr-xr-x 2 root root 4096 Jul 17 15:11 libbsoncxx-3.1.1-pre
drwxr-xr-x 2 root root 4096 Jul 17 14:46 libbson-static-1.0
drwxr-xr-x 2 root root 4096 Jul 17 14:51 libmongoc-1.0
drwxr-xr-x 2 root root 4096 Jul 17 14:51 libmongoc-static-1.0
drwxr-xr-x 2 root root 4096 Jul 17 15:11 libmongocxx-3.1.1-pre
```
I've even gone as far as exporting CMAKE_ROOT:

```
export CMAKE_ROOT=/usr/local/lib/cmake/:/usr/lib/cmake/:/usr/share/cmake-3.5/Modules
```

Trying various locations doesn't work:

- system wide: `cmake .. -DLIBBSON_DIR=/usr/local/lib/cmake/libbson-1.0`
- local build dir: `cmake .. -DLIBBSON_DIR=/home/alex/codez/robot_platform/platform/src/vendors/libbson/build`

The issue appears to be that libbson has the following cmake module `libbson-1.0-config.cmake` to which I setup a symbolic link, but still there is no difference.

**Comment by rkargon** [comment]
The source folder for the mongocxx driver has a folder called "cmake" which contains FindLibBSON.cmake and FindLibMongoC.cmake files. When I build mangrove, I need to specify `-DCMAKE_MODULE_PATH=/path/to/mongo-cxx-driver/cmake/` to the cmake command. Does this solve the problem?

**Comment by alexge233** [comment]
There is no such file in either mongo-cxx-driver or elsewhere (I've searched), so either I'm using the wrong branch of mongo-cxx-driver or somebody hardcoded a cmake module filename that doesn't exist.
For reference, I'm using mongo-cxx-driver `r3.1.0-226-g2677200` so maybe I need a newer one?
I *did* however find `libbson/build/libbson-config.cmake` however passing it either as `-DCMAKE_MODULE_PATH` or `-DLIBBSON_DIR` doesn't help.

Looking at the CMakeLists.txt I do not see `DLIBBSON_DIR` being used anywhere, so I guess there is no point in passing it. 
I've found the actual file in `/usr/local/lib/cmake/libbson-1.0` but passing either
- `cmake .. -DCMAKE_MODULE_PATH=/usr/local/lib/cmake`
- `cmake .. -DCMAKE_MODULE_PATH=/usr/local/lib/cmake/libbson-1.0`
produces the same error. 
I am starting to think that the problem is that the CMakeLists in mangrove is that `LIBBSON_REQUIRED_VERSION 1.3.4` is not satisfied?
However, checking out the version of libbson installed it is 1.8.0-dev so I'm not sure that is the case either... 

I went as far as removing all the installed stuff, re-installed from release only (libbson-1.6.3, mongo-c-driver-1.6.3, mongo-cxx-driver-r3.1.2) and then tried again what @rkargon suggested, which this time worked!

I have however run into compilation issues, but this particular problem was solved by using the release tarball which indeed contains the correct cmake module.

**Comment by JamieShelley** [comment]
I can confirm the same problem here, specifying  Prefix did nothing, inspecting the cmake file seems to assume waay to much. I'll try and use the tarball as mentioned.

**Comment by christomaliyekkal** [comment]
Hi @alexge233 @rkargon , I am facing similar issue. Could you please tell about the steps to resolve this issue?

**Comment by marioo63** [comment]
Hi. I also faced the same issue. I fixed my problem by modifying the following CMakeLists.txt files in the project:

Note: in my case, libbson, libmongoc, libbsonxx and libmongocxx were installed in /usr/local (installation prefix).

- mangrove-master/CMakelists.txt
- mangrove-master/src/boson/CMakelists.txt
- mangrove-master/src/mangrove/CMakelists.txt

For each one of them I, made the following simple modifications:

1 - I changed the following lines:
find_package(LibBSON ${LIBBSON_REQUIRED_VERSION} REQUIRED)
for find_package(LibBSON ${LIBBSON_REQUIRED_VERSION} REQUIRED CONFIGS libbson-1.0-config.cmake)
find_package(LibMongoC ${LIBMONGOC_REQUIRED_VERSION} REQUIRED)
for for find_package(LibMongoC ${LIBMONGOC_REQUIRED_VERSION} REQUIRED CONFIGS libmongoc-1.0-config.cmake)
Why?
It seems that cmake is looking for libbson-config.cmake and libmongoc-config.cmake. I noticed that the naming of the config files is inconsistent between libmongoc and libmongocxx. In the case of libbson and linmongoc, they added -1.0 in the name. I wonder what will happen when the version will become 2.0.

2 - I added the following line at the end:
include_directories(/usr/local/include/libbson-1.0 /usr/local/include/libmongoc-1.0)
Why?
For some reason the configured makefile is unable to figure out that bson.h is in /usr/local/include/libbson-1.0.

After those modifications, the project compiled without errors, except for some DEPRECATED warnings.

**Comment by gharis** [comment]
```
CMake Error at src/bsoncxx/CMakeLists.txt:114 (find_package):
  By not providing "Findlibbson-1.0.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "libbson-1.0", but CMake did not find one.

  Could not find a package configuration file provided by "libbson-1.0"
  (requested version 1.24.0) with any of the following names:

    libbson-1.0Config.cmake
    libbson-1.0-config.cmake

  Add the installation prefix of "libbson-1.0" to CMAKE_PREFIX_PATH or set
  "libbson-1.0_DIR" to a directory containing one of the above files.  If
  "libbson-1.0" provides a separate development package or SDK, be sure it
  has been installed.


-- Configuring incomplete, errors occurred!
```

You need to have mongo-c-driver-1.24.1 installed properly, this directory should contain  libbson-1.0-config.cmake and libmongoc-1.0-config.cmake

Following fixed issue for me 
hard code libsson-1.0 path in CMakeLists.txt mongo-cxx-driver-r3.8.0\src\bsoncxx

Replace line 114  under   # Require package of old libbson name (with lib).
`	  find_package(libbson-${LIBBSON_REQUIRED_ABI_VERSION} ${LIBBSON_REQUIRED_VERSION} REQUIRED)
`
With following 

 ```
     set(libbson_DIR "mongo-c-driver-1.24.1/install/lib/cmake/libbson-1.0")
     find_package(libbson-1.0 REQUIRED CONFIG PATHS ${libbson_DIR})
```

The error should be resolved.
